#!/bin/sh
cp src/DetectorConstruction.cc.10 src/DetectorConstruction.cc
cp src/WLSMaterials.cc.10 src/WLSMaterials.cc
cp src/PhysicsList.cc.Centos7 src/PhysicsList.cc
make
ssh jlabanalysis << EOF
cd ~/CDetMC
cp src/PhysicsList.cc.11 src/PhysicsList.cc
make
EOF
